<h2>Nabídka našich pojištění</h2>
<div class="container">
    <section class="row seda">
            <div class="col span-2-of-4 ramece">
                <img class="img" src="../img/auto.png" alt="auto">
            </div>
            <div class="col span-2-of-4 ramece">
                <h3>pojištění vozu</h3>
                <p>-proti krádeži</p>
                <p>-proti nehodě</p>
                <br>
                <h4>Vůbec se nebojte se u Nás pojistit, budete-li platit včas, auto vám nikdy samovolně neshoří.</h4>
                <br>
                <h4>TOP pojištění za nejlepší cenu.</h4>
            </div>
            <div class="row"><h3>cena již od 200kč</h3></div>
    </section>
    
    <br>
    <section class="row seda">
            <div class="col span-2-of-4 ramece">
                <br>    
                <h3>pojištění nemovitosti</h3>
                <br>
                <p></p>
                <h4>zatím není v nabídce, leč pracuji na tom usilovně...</h4>
                <br>
                <div class="row"><h3>cena již od 300kč</h3></div>
            </div>
            <div class="col span-2-of-4 ramece">
                <img class="img" src="../img/dum.png" alt="auto">
            </div>
    </section>

</div>
<h2>2022</h2>