<a class="tlacitko" href="pojisteni">zpět</a>
    <h2>Nastavení profilu</h2>
    
    <form method="post">
        <span>jméno:</span>
        <input type="text" name="jmeno" value="<?= $jmeno ?>">
        <span>příjmení:</span>
        <input type="text" name="prijmeni" value="<?= $prijmeni ?>">
        <span>email:</span>
        <input type="text" name="email" value="<?= $email ?>">
        
        <input type="submit" name="zmenaNastaveni" value="zmenit nastaveni">
    </form>