<div class="container">
<a class="tlacitko" href="pojisteni">zpět</a>
<h2><?= $nazevPojisteni ?></h2>
    <img class="img" src="../img/auto.png" alt="domacnost" width="9%">
    <section>
        <p>pojištěno na <?= $delkaPojisteni ?></p><br>
        <p>pravidelná měsíční splátka <?= $mesicniSplatka ?>Kč.</p><br>
        <p>Druh/Typ automobilu: <?= $druhAuta ?></p><br>
        <p>Datum vytvoření pojištění <?= $datumVytvoreni ?></p><br>
    </section>
</div>