<h2>Vítám tě...</h2>
        <br>
        <div class="img">
            <img src="../img/auto.png" alt="auto" width="25%">
            <img src="../img/dum.png" alt="dum" width="20%">
        </div>
        <h2>Hledáš výhodné pojištění?</h2>
<div class="container">
        <h3>Pojišťovna doslova s ručením omezeným</h3>
        <p>má v Českých zemích letitou tradici...</p>
        <br>
        <h4> Pojišťují se u Nás všichni co něco znamenají a to již od roku 1884.</h4>
        <br>
        <h4>Zbyšek Doslova z Vyhořelic zakládá svůj první pojištovnický spolek ovšem již kolem roku 1880 tedy o čtyři roky dříve a to s jistým  Jaroslavem Cimrmanem synem Leopolda Cimrmana. Nadějný a pohledný Cimrman, coby začínající dramatik, básník, hudebník, učitel, cestovatel, filozof, vynálezce, vědec, kriminalista, sportovec a pojišťovník, se na přelomu let 83/84 vydal cestou jinou. Uměleckou. Vyhořelický Doslova a Vídeňský Jára se tady rozdělují a vzniká Pojištovna Doslova </h4>
        <br>
        <h4>...možná právě zde začíná Váš příběh, příběh spáleného domu nebo ukradeného auta.</h4>
        <br>
        <h4>Přečtěte si také příběhy našich klientů...</h4>
        <br>
        <section>
                <img class="img" src="../img/smatana.jpg" alt="Smatana a Notre Dame">
                <h3>Naše pracovnice u neplatičů pojistného..</h3>
                <h4>Veřejně uznávaná reportérka, byla svědkem smutné události. Jak se dalo čekat, platební neschopnost splácet prvidelné měsíční <strike>výpal</strike> pojistné, vyvrcholilo v nečekané samovznícení. Jak je již zvykem, naše pojištovna měla reportérku zrovna na dovolené v místě konání. Empatická reportérka spolupracujíc s naší společností ihned zaslala fotografie s všeříkajícím výrazem aby tak doplnila koláž tragédie, která z fotky přímo sálá.</h4>
                
        </section>
</div>